first version
shopgate-professional-services/ext-variant-images pull request #1
Opened 2023-01-19 11:54 UTC by Phmank

2023-09-07 08:38 UTC, patrick-scherer requested changes

2023-09-07 08:38 UTC, patrick-scherer commented on frontend/components/VariantSelect/components/BaseSelector/index.jsx
> +    select({ id: characteristicsId, value: value.id });
ESLint

2023-09-07 08:38 UTC, patrick-scherer commented on frontend/components/VariantSelect/components/BaseSelector/index.jsx
> +      <button
ESLint

2023-09-07 08:38 UTC, patrick-scherer commented on frontend/components/VariantSelect/components/ImageSwatchSelector/index.jsx
> +    this.props.sendReport({ id: characteristicsId, value: value.id });
ESLint

2023-09-07 08:38 UTC, patrick-scherer commented on frontend/components/VariantSelect/components/ImageSwatchSelector/index.jsx
> +class ImageSwatchSelector extends Component {
Missing props validations

2023-09-07 08:38 UTC, patrick-scherer commented on frontend/components/VariantSelect/components/ImageSwatchSelector/index.jsx
> +class ImageSwatchSelector extends Component {
Missing props validations

2023-09-07 08:38 UTC, patrick-scherer commented on frontend/components/VariantSelect/index.jsx
> +          :
Add a non-breaking space here?

![h1-no-space](https://github.com/shopgate-professional-services/ext-variant-images/assets/33117900/203e2aa2-d483-423a-9ab9-e41d8020edba)

2023-09-07 08:38 UTC, patrick-scherer commented on frontend/components/VariantSelect/index.jsx
> + * @param {Object} props Component props
ESlint

2023-09-07 08:38 UTC, patrick-scherer commented on frontend/components/VariantSelect/selectors.js
> +          imageOverlayLabel = property.label.split('~')[1];
ESLint

2023-09-07 08:38 UTC, patrick-scherer commented on README.md
> +This extension needs to have an "eval job" set up by the Shopgate Support.
Info about property format (`swatchImage~`)

2023-09-14 09:26 UTC, Phmank commented on frontend/components/VariantSelect/components/BaseSelector/index.jsx
> +    select({ id: characteristicsId, value: value.id });
done

2023-09-14 09:41 UTC, merged